<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Connexion | École Mandroso</title>
  <link rel="icon" type="image/png" href="<?= url('public/uploads/favicone/favicon.png') ?>">
  <script src="https://cdn.tailwindcss.com"></script>
  <script>
    tailwind.config = {
      theme: {
        extend: {
          fontFamily: {
            sans: ['Outfit', 'sans-serif'],
            mono: ['Outfit', 'sans-serif'],
            serif: ['Outfit', 'sans-serif'],
          },
        }
      }
    }
  </script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
  <style>
    html, body { 
        height: 100%;
        width: 100%;
        margin: 0; 
        padding: 0; 
        overflow: hidden; 
    }
    :root { font-size: 9px; }
    @media (min-width: 640px) { :root { font-size: 13px; } }
    @media (min-width: 1024px) { :root { font-size: 14px; } }
  </style>
</head>
<body class="bg-gradient-to-br from-blue-100 via-blue-200 to-green-100 relative h-full w-full overflow-hidden">

  <!-- Background container (Fixé pour ne pas gêner le centrage) -->
  <div id="background-container" class="fixed inset-0 overflow-hidden z-0 pointer-events-none">
    <!-- Generated by JS -->
  </div>

  <!-- Conteneur de centrage (Garantit que la carte reste au milieu) -->
  <div class="relative z-10 h-full w-full flex items-center justify-center p-4">
    <div id="loginCard" class="bg-white/90 backdrop-blur-md shadow-2xl rounded-2xl p-8 w-full max-w-md border border-white/50">
    <div class="text-center mb-6">
      <div class="text-6xl mb-4 transform hover:scale-110 transition-transform cursor-default inline-block">🎓</div>
      <h1 class="text-3xl font-bold text-blue-700">École Mandroso</h1>
      <p class="text-gray-500 text-sm mt-1">Connectez-vous à votre espace</p>
    </div>

    <?php if (isset($error)): ?>
        <div class="bg-red-50 border-l-4 border-red-500 text-red-700 p-4 mb-6 rounded-lg text-sm shadow-sm animate-pulse">
            <div class="flex items-center">
                <i class="fas fa-exclamation-circle mr-2"></i>
                <p><?= e($error) ?></p>
            </div>
        </div>
    <?php endif; ?>

    <form method="POST" action="<?= url('auth/login') ?>" class="space-y-6">
      <?= csrf_field() ?>
      
      <div>
        <label for="username" class="block text-sm font-medium text-gray-700 ml-1 mb-1">Identifiant</label>
        <div class="relative">
          <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <i class="fas fa-user text-gray-400"></i>
          </div>
          <input type="text" id="username" name="username" placeholder="Nom d'utilisateur ou Email" 
            value="<?= e(old('username')) ?>"
            required
            class="w-full pl-10 pr-4 py-3 border <?= error('username') ? 'border-red-400' : 'border-gray-300' ?> rounded-xl focus:ring-2 focus:ring-blue-400 focus:border-transparent outline-none transition-all bg-white/50 hover:bg-white" />
        </div>
        <?php if ($err = error('username')): ?>
            <p class="text-red-500 text-[11px] mt-1 ml-1"><?= e($err[0]) ?></p>
        <?php endif; ?>
      </div>

      <div>
        <label for="password" class="block text-sm font-medium text-gray-700 ml-1 mb-1">Mot de passe</label>
        <div class="relative">
          <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
            <i class="fas fa-lock text-gray-400"></i>
          </div>
          <input type="password" id="password" name="password" placeholder="••••••••" required
            class="w-full pl-10 pr-4 py-3 border <?= error('password') ? 'border-red-400' : 'border-gray-300' ?> rounded-xl focus:ring-2 focus:ring-green-400 focus:border-transparent outline-none transition-all bg-white/50 hover:bg-white" />
        </div>
        <?php if ($err = error('password')): ?>
            <p class="text-red-500 text-[11px] mt-1 ml-1"><?= e($err[0]) ?></p>
        <?php endif; ?>
      </div>

      <div class="flex items-center justify-between text-sm">
        <label class="flex items-center cursor-pointer">
            <input type="checkbox" class="rounded border-gray-300 text-blue-600 focus:ring-blue-500">
            <span class="ml-2 text-gray-600">Se souvenir</span>
        </label>
        <a href="<?= url('auth/password-reset') ?>" class="text-blue-600 hover:text-blue-800 hover:underline">
            Oublié ?
        </a>
      </div>

      <button type="submit"
        class="w-full bg-gradient-to-r from-blue-600 to-green-500 text-white py-3 rounded-xl font-bold tracking-wide hover:scale-[1.02] active:scale-95 transition-all shadow-lg hover:shadow-xl">
        <i class="fas fa-sign-in-alt mr-2"></i> Se connecter
      </button>
    </form>

    <div class="mt-8 text-center border-t border-gray-200 pt-4">
        <p class="text-xs text-gray-500">© <?= date('Y') ?> École Mandroso. Tous droits réservés.</p>
    </div>
    </div>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', () => {
        // Animation d'entrée du formulaire
        gsap.from('#loginCard', { 
            y: 50, 
            opacity: 0, 
            duration: 1.2, 
            ease: 'power4.out' 
        });

        // Animation légère du chapeau
        gsap.to('.text-6xl', {
            rotation: 10,
            repeat: -1,
            yoyo: true,
            duration: 2,
            ease: 'sine.inOut'
        });

        // Génération dynamique des icônes d'arrière-plan
        const container = document.getElementById('background-container');
        const icons = [
            'fa-pencil-alt', 'fa-pen-nib', 'fa-highlighter', 'fa-marker', 
            'fa-eraser', 'fa-cut', 'fa-ruler-vertical', 'fa-ruler-combined',
            'fa-book', 'fa-book-open', 'fa-sticky-note', 'fa-calculator',
            'fa-microscope', 'fa-atom', 'fa-square-root-alt', 'fa-infinity',
            'fa-graduation-cap', 'fa-globe', 'fa-laptop', 'fa-palette', 
            'fa-music', 'fa-football-ball', 'fa-trophy', 'fa-flask', 'fa-dna',
            'fa-star', 'fa-lightbulb', 'fa-clock', 'fa-bell', 'fa-clipboard-check'
        ];
        
        const colors = [
            'text-yellow-500', 'text-yellow-600', 'text-blue-500', 'text-blue-600',
            'text-green-500', 'text-green-600', 'text-red-400', 'text-red-500',
            'text-purple-400', 'text-purple-500', 'text-pink-400', 'text-pink-500',
            'text-indigo-400', 'text-teal-500', 'text-orange-400', 'text-gray-400'
        ];

        const sizes = ['text-2xl', 'text-3xl', 'text-4xl', 'text-5xl'];

        // Création basée sur une grille pour une distribution uniforme
        const cols = 10; // Augmenter le nombre de colonnes pour plus de granularité
        const rows = 8;
        const cellWidth = 100 / cols;
        const cellHeight = 100 / rows;

        for (let r = 0; r < rows; r++) {
            for (let c = 0; c < cols; c++) {
                // Probabilité d'avoir une icône (plus élevée pour garantir la couverture)
                // On force un peu plus sur les bords (colonne 0 et dernière)
                let probability = 0.6; // 60% de chance de base
                if (c === 0 || c === cols - 1) probability = 0.8; // 80% sur les bords gauche/droit

                if (Math.random() > probability) continue; 

                const el = document.createElement('i');
                
                // Propriétés aléatoires
                const randomIcon = icons[Math.floor(Math.random() * icons.length)];
                const randomColor = colors[Math.floor(Math.random() * colors.length)];
                const randomSize = sizes[Math.floor(Math.random() * sizes.length)];
                const randomOpacity = (Math.random() * 0.25 + 0.1).toFixed(2);
                const randomRot = Math.random() * 360;

                // Position dans la cellule
                // On utilise toute la largeur de la cellule pour bien remplir
                const randomTop = (r * cellHeight) + (Math.random() * (cellHeight * 0.9));
                const randomLeft = (c * cellWidth) + (Math.random() * (cellWidth * 0.9));

                // Classes de base
                el.className = `fas ${randomIcon} ${randomColor} ${randomSize} absolute opacity-[${randomOpacity}]`;
                
                // Styles inline
                el.style.top = `${randomTop}%`;
                el.style.left = `${randomLeft}%`;
                el.style.opacity = randomOpacity;
                el.style.transform = `rotate(${randomRot}deg)`;

                container.appendChild(el);

                // Animation individuelle GSAP
                gsap.to(el, {
                    y: Math.random() * 60 - 30, 
                    x: Math.random() * 60 - 30,
                    rotation: Math.random() * 90 - 45 + randomRot,
                    scale: Math.random() * 0.4 + 0.8,
                    duration: Math.random() * 6 + 4,
                    repeat: -1,
                    yoyo: true,
                    ease: 'sine.inOut',
                    delay: Math.random() * 5
                });
            }
        }
    });
  </script>

</body>
</html>
